version: 0.9.0.{build}

# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyVersionInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

before_build:
- cmd: nuget restore OpenDBDiff.sln

build:
  parallel: true # enable MSBuild parallel builds
  project: OpenDBDiff.sln
  verbosity: minimal

artifacts:
- path: OpenDBDiff\bin\Debug
  name: OpenDBDiffCI